version: "3.0"

volumes:
  database:

networks:
  app_net:

services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234@abcd
      MYSQL_DATABASE: perola_negra
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql

  api-v1:
    build: ./
    environment:
      - ENVIRONMENT=dev
      - MYSQL_ROOT_PASSWORD=1234@abcd
    networks:
      - app_net
    container_name: "projeto-perola-negra_api"
    user: "1000:1000"
    ports:
      - 3030:80
    volumes:
      - ./:/var/www/html
