version: "3.0"

volumes:
  database:

networks:
  app_net:

services:
  mysql:
    container_name: "perola_negra_db"
    networks:
      - app_net
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=1234@abcd
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql

  api-v1:
    build: ./
    environment:
      - ENVIRONMENT=dev
      - MYSQL_ROOT_PASSWORD=1234@abcd
    networks:
      - app_net
    container_name: "projeto-perola-negra_api"
    user: "1000:1000"
    ports:
      - 3030:80
    volumes:
      - ./:/var/www/html
