CREATE TABLE IF NOT EXISTS leads (
    id INT(8) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(256) NOT NULL, 
    telefone VARCHAR(20) NOT NULL, 
    email VARCHAR(256) NOT NULL, 
    mensagem VARCHAR(512) NOT NULL
);
